# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3a8c6af6687060374e34fc2e978dadde6f4102f2872ecc715869d11020b69a4be5f80b6145369556a6f5973ed7038f7c394ad460d43277b6c9df182fd0f4657

test:
  secret_key_base: b1fc4b19bcba786b4cbc29ff6555b55adacd12e1bb58e92e4534e4035526d04c37e37c878d630e4d91a848e535d34f6444369c5c9eca68e2156472dd186fb3b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
